# mPaaS Pods Begin
plugin "cocoapods-mPaaS"
source "https://code.aliyun.com/mpaas-public/podspecs.git"
#use_pod_for_mPaaS!
mPaaS_baseline '10.1.68'  # 请将 x.x.x 替换成真实基线版本
mPaaS_version_code 19   # This line is maintained by MPaaS plugin automatically. Please don't modify.


target 'MPScanCodeDemo_pod' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MPScanCodeDemo_pod
  mPaaS_pod "mPaaS_ScanCode"
  mPaaS_pod "mPaaS_CommonUI"

end
